name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
       Default: ${{ github.repository }}

    - name: Build Application
      run: |
        # Your build commands here
        echo "Building the application..."
