name: Daily Backup

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight every day

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Backup Database
        run: |
          PythonScripts/cronjob.py
          echo "Performing daily backup..."
