name: nested_workflow_01
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Application
      run: |
        # Your build commands here
        echo "Building the application..."
