name: parent_workflow01

on:
  push:
    branches:
      - main

jobs:
  deploy-job-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Trigger Nested Workflow
        run: |
        "https://api.github.com/repos/${{ github.repository }}/actions/workflows/child_workflow.yml/dispatches" \
          -d '{"ref":"main"}'
        with:
          environment: 'math-main'
          #app_id: prospector-data-api
          ar_repo: Intermediate_GitHub_Workflow
          project_id: ${{ secrets.PAT_TOKEN_GITHUB }}
