name: Parent Workflow

on:
  push:
    branches:
      - main

jobs:
  parent_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Child Workflow
        uses: ./.github/workflows/child_workflow.yml  # Relative path to the child workflow file

      - name: Checkout Repository
        uses: actions/checkout@v2
